version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  redis:
    image: redis:latest


  airflow_db_init:
    image: thelastmonk/airflow-dag:latest
    command: ["sh", "-c", "sleep 10 && airflow db init"]  # Wait for PostgreSQL
    depends_on:
      - postgres
    restart: "no"


  airflow_webserver:
    image: thelastmonk/airflow-dag:latest
    command: ["sh", "-c", "sleep 10 && airflow webserver --port 8080"]
    container_name: airflow_webserver
    depends_on:
      - airflow_db_init
    restart: always
    ports:
      - "8080:8080"
    environment:
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/home/development/airflow/docker_cicd_test/dags

  airflow_scheduler:
    image: thelastmonk/airflow-dag:latest
    command: ["airflow", "scheduler"]
    container_name: airflow_scheduler
    depends_on:
      - airflow_db_init
    restart: always

  
