version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"

  redis:
    image: redis:latest


  airflow_db_init:
    image: thelastmonk/airflow-dag:latest
    command: ["airflow", "db", "init"]
    depends_on:
      - mysql
    restart: "no"


  airflow_webserver:
    image: thelastmonk/airflow-dag:latest
    command: ["airflow" ,  "webserver",]
    container_name: airflow_webserver
    depends_on:
      - mysql 
    restart: always
    ports:
      - "8080:8080"
    environment:
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://airflow_user:your_password@mysql:3306/airflow_db
    volumes:
      - ./dags:/home/development/airflow/docker_cicd_test/dags

  airflow_scheduler:
    image: thelastmonk/airflow-dag:latest
    command: ["airflow", "scheduler"]
    container_name: airflow_scheduler
    depends_on:
      - airflow_webserver
    restart: always

  
