version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  redis:
    image: redis:latest

  webserver:
    image: thelastmonk/airflow-dag:latest
    command: ["airflow", "webserver"]
    container_name: airflow_webserver
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow

  scheduler:
    image: thelastmonk/airflow-dag:latest
    container_name: airflow_scheduler
    depends_on:
      - webserver
