version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  redis:
    image: redis:latest


  airflow_db_init:
    image: thelastmonk/airflow-dag:latest
    command: ["airflow db init"]
    depends_on:
      - postgres
    restart: "no"


  airflow_webserver:
    image: thelastmonk/airflow-dag:latest
    command: ["airflow" ,  "webserver",]
    container_name: airflow_webserver
    depends_on:
      - airflow_db_init
    restart: always
    ports:
      - "8080:8080"
    environment:
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqldb://airflow_user:your_password@localhost:3306/airflow_db
    volumes:
      - ./dags:/home/development/airflow/docker_cicd_test/dags

  airflow_scheduler:
    image: thelastmonk/airflow-dag:latest
    command: ["airflow", "scheduler"]
    container_name: airflow_scheduler
    depends_on:
      - airflow_db_init
    restart: always

  
